### PR TITLE
enhancements/update/operators: Collect operator-dev-doc

### PR DESCRIPTION
**Pull request by wking**
To cover the cluster-version operator <-> second-level operator interactions.

Move the previous operator-dev-doc down into this document as a README, and drop a symlink in the old location for backwards-compat with existing linkers.

### CODE REVIEW

**Comment by wking** [comment]
Rebased on master and moving to `enhancements/update` instead (following #422) with 15e4900 -> 8030074.

**Comment by russellb** [comment]
> `operator-dev-doc.md` doesn't look right in your latest commit

now I see it's a sym link and the github diff viewer just showed it poorly, sorry about that.

**Comment by wking** [comment]
> ... the github diff viewer just showed it poorly...

Yeah, news to me.  Once you pointed it out, I found [this request][1] for clickable symlink targets, which makes sense to me.  But since we need to work with GitHub's current file browser, I've pushed 8030074 -> c4126fb to use stub Markdown instead of a symlink.

[1]: https://github.com/dear-github/dear-github/issues/156#issuecomment-222349916

**Comment by russellb** [comment]
Thanks.

As for the change, it's not obvious to me that `update/` is a better home for the doc.  It seems a bit more broad than that?

**Comment by wking** [comment]
/hold

I'll round with @sallyom about #52 and finding a comfy home for this stuff...

**Pull request closed without merging**
