### PR TITLE
Proposal for an operator health metric

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

### CODE REVIEW

**Comment by sradco** [comment]
Hi @jan--f , Can you please have a look at this enhancement proposal?

**Comment by jan--f** [comment]
Hey, I'll voice my two main concerns that I brought up on the issue and in our chat again here:

1. This assumes that we have a prometheus/alertmanager stack anf that operators need to ship alerting rules. Not all operators do that today. It'll be hard to encourage developers to do that I think. Additionally there are systems that don't ship a default prometheus stack (sat Microshift) and efforts are undeway to make CMO optional in OpenShift (https://issues.redhat.com/browse/MON-2854).
2. To me its still unclear what we mean when we talk about operator health here. An operator is often fairly simple in what it achieves, there are only a limited set of error scenarios. This should define what the term Operator Health actually means.

**Comment by sradco** [comment]
> Hey, I'll voice my two main concerns that I brought up on the issue and in our chat again here:
> 
> 1. This assumes that we have a prometheus/alertmanager stack anf that operators need to ship alerting rules. Not all operators do that today. It'll be hard to encourage developers to do that I think. Additionally there are systems that don't ship a default prometheus stack (sat Microshift) and efforts are undeway to make CMO optional in OpenShift (https://issues.redhat.com/browse/MON-2854).

We ship OpenShift with Prometheus stack and invest in creating metrics, alerts, dashboards, runbooks, testing, etc for it. Just since some use cases will not use it, doesn't mean we will stop investing in it.

The idea is for operators, that do integrate Prometheus stack with OCP, to be able to report a more accurate operator health status and not be based only real time, which is not that accurate.
Also, if based on the alerts we state that there is a health metrics, we can also point to the problematic alerts and we already include runbooks to help the users to fix the issue. The real time metrics will not allow this.

This doesn't mean that the operator can't still report the metric based on real time data. Like its done for example for Storage
console-openshift-console apps cnv2 engineering redhat com_dashboards

> 2. To me its still unclear what we mean when we talk about operator health here. An operator is often fairly simple in what it achieves, there are only a limited set of error scenarios. This should define what the term Operator Health actually means.

Operator health aggregates all the operator components health. 

As I look at it this, the labels that we propose to add:
- Operator name
- Impact on operator health - Critical/ Warning/ None
will benefit the users even if they would eventually use Grafana or any other visualization tool. They can also use them to route the alerts based on them.

For Red Hat this would provide a more accurate health status, since it takes the time factor into consideration and can provide our customer a better experience.

**Review by simonpasquier — COMMENTED** [review]
I'm not sure to understand who's supposed to generate this health metric. Is it the responsibility of each operator? OLM?
Similar question about how the metric is generated: is it done via recording rule?

**Comment by wking** [comment]
> I'm not sure to understand who's supposed to generate this health metric. Is it the responsibility of each operator? OLM?

In case it's useful precedent, ClusterOperator operators write [`conditions`][1], and the cluster-version operator reads those from ClusterOperator, [exports them to `cluster_operator_conditions`][2], and [defines some alerts covering those metrics][3].  A benefit is that there's a consistent alert/metric experience across all of the ClusterOperators.  A downside is that the best the alert can do is say "a ClusterOperator is sad.  Go look at its `conditions[].message` for more details", and there's not much to say runbook-wise for something that generic.

The other approach you point out is to have each leafy operator export its own metrics and covering alerts.  Hopefully in addition to reporting status up to OLM via Kube-resource metadata for [clusters without monitoring stacks][4].  But in this approach, the alert content and metrics can be tuned to the specific operator, but there is lots of room for inconsistency between operators.

And obviously it's also possible to do both simultaneously, where everyone (or operators that opt in?) can send data up to OLM to be exported in centralized metrics while they also export their own metrics and add on their own supplemental alert coverage.

[1]: https://github.com/openshift/api/blob/a671aa80d9956a81ed6e17fa0d8a71fbc7a0fbc0/config/v1/types_cluster_operator.go#L37-L44
[2]: https://github.com/openshift/cluster-version-operator/blob/e6aeb8dd171b9e442767cf8e88b034c4844de749/pkg/cvo/metrics.go#L99-L102
[3]: https://github.com/openshift/cluster-version-operator/blob/e6aeb8dd171b9e442767cf8e88b034c4844de749/install/0000_90_cluster-version-operator_02_servicemonitor.yaml#L87-L120
[4]: https://github.com/openshift/enhancements/pull/1280#issuecomment-1326644938

**Comment by simonpasquier** [comment]
> A downside is that the best the alert can do is say "a ClusterOperator is sad. Go look at its conditions[].message for more details", and there's not much to say runbook-wise for something that generic.

In any case, this isn't something that can be fixed with metrics as metric labels shouldn't be free-form.

**Comment by wking** [comment]
> >  A downside is that the best the alert can do is say "a ClusterOperator is sad. Go look at its conditions[].message for more details", and there's not much to say runbook-wise for something that generic.
>
> In any case, this isn't something that can be fixed with metrics as metric labels shouldn't be free-form.

But an component-specific alert could link a runbook with component-specific investigation notes, while an alert that covers many components would have to link a generic runbook and expect the user to locate the relevant component-specific section inside that generic runbook.  Which isn't the end of the world.  And if we could get make runbook links dynamic by injecting labels into the URI or some such, a generic alert could still link to component-specific runbooks.

**Comment by sradco** [comment]
>And obviously it's also possible to do both simultaneously, where everyone (or operators that opt in?) can send data up to OLM to be exported in centralized metrics while they also export their own metrics and add on their own supplemental alert coverage.

Yes. I think having the alerts based health metrics will allow to point the users to the relevant alerts that are firing and how they impact the operator health and since alerts can provide runbooks the users will have more tools for solving the issues.

I saw the `cluster_operator_conditions` and it looks good. The issue as you pointed out is that the data there is aggregated and doesn't provide much information on what the issue is. Another option that I thought of is to add the `operator_health_impact` label and to use it for the tooltip when you press on the operator status icon.

We can suggest this as a recommend way of doing this tooltip.
There are already operators that added the tooltip like the "storage" and "insights" operators, and its not clear what actions the user can do from the tooltips they provide. Its not actionable.

**Comment by sradco** [comment]
Hi @wking, @simonpasquier, @jan--f,

Based on the  [Critical alerts defivintion](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#critical-alerts), Most operators that are not core (Core oprator for example is ODF) should not expose "critical" severity alerts.

We can actually, and perhaps even should test for this when certifying operators.
This would keep the alerts much more organised and clear on for users when an actual critical alert occurs.

That said, operators have alerts that impact their health and from the operator perspective mean that important functionality was lost and should be fixed or the operator is considered in error/warning health status.

The  `operator_health_impact` label would be the label for this. It would be used by operators only and would indicate if the operator health is affected and how. 

This is the name we gave it in CNV, but perhaps it can also be called `operator_severity`.

We have decided to incorporate the operator health based on its conditions and the operator health based on the alerts with `operator_health_impact` error/warning to create an aggregated rule that calculates the operator health.
If operator has good alerts coverage the aggregated rule would be more accurate then the conditions alone and would also provide hints for the issue, since it is tied to alerts and their runbooks. 

Please let me know what you think:
1. Can we recommend to users to add the new `operator_health_impact` and change all non core operator critical severity alerts to `warning` alerts?
2. Can we recommend an aggregative recording rule that takes alerts and operator conditions into account?

**Comment by dhellmann** [comment]
@sradco this design was closed by the bot without merging but I see the ticket it is linked to is marked closed done. Should this design be fixed up and merged?

**Comment by sradco** [comment]
Yes, we need to get to an agreement and get it merged. I had outher priorities that I had to address, but I would really like to get it merged.

**Comment by dhellmann** [comment]
OK, @simonpasquier should be able to help with that, but let me know if I can do anything.

**Comment by dhellmann** [comment]
This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, remove the lifecycle/rotten label to have this bot ignore it in the future.

**Comment by dhellmann** [comment]
> This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, remove the lifecycle/rotten label to have this bot ignore it in the future.

I'm working on a new bot, sorry for the extra noise.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, CNV-14693, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
I've cleared the lifecycle flag to keep the bot from posting repeatedly.

**Pull request closed without merging**
