### PR TITLE
Update MHC annotation

### PR DESCRIPTION
**Pull request by enxebre**
Update MHC annotation and stress is to enable external experimental systems

### CODE REVIEW

**Comment by markmc** [comment]
Really great to see the enhancement being kept up to date. Thanks

I think we can do better than `Update MHC annotation` in `git log` though? A super brief explanation of what changed since the enhancement merged would be great.

e.g.

> We have renamed the annotation to `machine.openshift.io/remediation-strategy: external-baremetal` to reflect the possibility there might be other external remediation strategies in future. The reboot based external remediation strategy is currently focused on bare metal use cases. See also openshift/machine-api-operator#476

**Comment by JoelSpeed** [comment]
Assuming we implement this shortly after merging the update, are we aware of what this will break and who we should notify so they can fix it?

**Comment by enxebre** [comment]
>Assuming we implement this shortly after merging the update, are we aware of what this will break and who we should notify so they can fix it?

This is to consolidate with current state of code. https://github.com/openshift/machine-api-operator/pull/476

**Comment by JoelSpeed** [comment]
Ack, in that case all is well

/lgtm

**Pull request merged**
