### PR TITLE
Enhancement: Enable IPsec support in OVNKubernetes

### PR DESCRIPTION
**Pull request by markdgray**
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>

### CODE REVIEW

**Comment by markdgray** [comment]
Accidently closed https://github.com/openshift/enhancements/pull/473 and am unable to open it. This PR has resolved all previous comments, squashed into a single commit, and removed the WIP tag

**Comment by russellb** [comment]
> Accidently closed #473 and am unable to open it. This PR has resolved all previous comments, squashed into a single commit, and removed the WIP tag

would you like me to re-open that one for you?

**Comment by markdgray** [comment]
> > Accidently closed #473 and am unable to open it. This PR has resolved all previous comments, squashed into a single commit, and removed the WIP tag
> 
> would you like me to re-open that one for you?

If you can, do you have special privileges?

**Pull request closed without merging**
