### PR TITLE
Host port registry: Add loopback metrics port for SDN

### PR DESCRIPTION
**Pull request by martinkennelly**
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

Depends on https://github.com/openshift/sdn/pull/358

### CODE REVIEW

**Comment by martinkennelly** [comment]
@abhat Could you review this? One line change. Thanks.

**Comment by martinkennelly** [comment]
@mfojtik I see you have approver power. Can you review this one line please?

**Comment by abhat** [comment]
@knobunc - can you PTAL?

**Pull request merged**
