### PR TITLE
enhancements/template: Drop 'enhancement(s)-' prefix

### PR DESCRIPTION
**Pull request by wking**
This gets us in line with the README's:

```markdown
2. Follow the process outlined in the [enhancement
   template](enhancement-template.md)
```

And the template is for a single enhancement, so the singular form makes more sense.

### CODE REVIEW

**Comment by wking** [comment]
Might want to just rename to `template.md`?  Seems like the leading `enhancement(s)-` is redundant given the scoping `enhancements/` directory.

**Comment by chancez** [comment]
Either seems reasonable.

**Comment by wking** [comment]
Dropped the prefix altogether with 92386b3 -> 919e851.

**Comment by derekwaynecarr** [comment]
thanks @wking 

/lgtm
/approve

**Comment by sdodson** [comment]
/approve
now that the bot is wired up

**Pull request merged**
