### PR TITLE
WIP: Add FCCT support in MC proposal

### PR DESCRIPTION
**Pull request by LorbusChris**
[Rendered](https://github.com/LorbusChris/enhancements/blob/67fb4c96a69362dec13d26a5e4baeba79c0602bb/enhancements/machine-config/fcct-support-in-mc.md)

### CODE REVIEW

**Comment by LorbusChris** [comment]
Note to myself:
- Add explanation that only a subset of Ignition (and thus FCC) features is supported by MCO
- Add mention of FCC variants (current implementation in PR https://github.com/openshift/machine-config-operator/pull/1980 does not use a variant parser, but the variant-agnostic base parser). Currently only a `fcos` variant exists, but a `rhcos` variant is planned.

**Comment by cgwalters** [comment]
I think this is conditional on https://github.com/coreos/fcct/pull/79 - maintaining that split is probably the bulk of the effort here, including dealing with the set of things in FCOS but not RHCOS (switching streams, zincati, etc. - there may be more in the future but hopefully we keep it constrained)

**Comment by cgwalters** [comment]
I've been thinking about this more.  It feels like we should do a more clean break here and introduce a new `coreosconfig` CRD that is just this.  The way MachineConfig is *either* Ignition or the "custom MC stuff" (or both) is confusing.  Plus it has things users shouldn't set like `osImageURL`.

(Internally coreosconfigs would compile into machineconfig of course)

**Comment by LorbusChris** [comment]
> I've been thinking about this more. It feels like we should do a more clean break here and introduce a new `coreosconfig` CRD that is just this. The way MachineConfig is _either_ Ignition or the "custom MC stuff" (or both) is confusing. Plus it has things users shouldn't set like `osImageURL`.
> 
> (Internally coreosconfigs would compile into machineconfig of course)

I'm closing this proposal in favor of the approach described above
/close

**Pull request closed without merging**
