### PR TITLE
Updates to workloads vs configuration API documentation

### PR DESCRIPTION
**Pull request by JoelSpeed**
This is a follow up to #1218 to address some additional feedback after it was merged

CC @Miciah

### CODE REVIEW

**Comment by dhellmann** [comment]
/approve

This looks fine. I'll leave it up to the original reviewers to lgtm it.

**Review by Miciah — COMMENTED** [review]
I still wonder to what extent this is descriptive, and to what extent it's prescriptive.  Are we going to hold API authors stringently to these conventions?  For example, let's say I were introducing the IngressController API today, as a new API.  

* First, is IngressController a workload API or a configuration API?  It isn't cluster-scoped, and it isn't singleton, but the cluster admin does use it to configure cluster infrastructure (namely the default ingresscontroller, which handles several critical routes).
* For the sake discussion, let's say that IngressController is a configuration API; would I be expected to identify it as such explicitly in the PR description or API documentation? 
*  Would I be expected to make IngressController cluster-scoped and singleton, or justify why it is unlike a typical configuration API in these respects?
* When we originally added IngressController, we envisioned that we _might_ allow regular users to create ingresscontroller objects in their own namespaces; does the configuration vs. workload dichotomy preclude that use-case, would it force us to categorize IngressController as a workload API, or what?

**Comment by JoelSpeed** [comment]
> I still wonder to what extent this is descriptive, and to what extent it's prescriptive. Are we going to hold API authors stringently to these conventions? For example, let's say I were introducing the IngressController API today, as a new API.

Is your suggestion to drop the bit that describes what these typically look like? We know we have exceptions to this (I recently added a configuration API that's not cluster scoped for example) but these are more, general rules for how you might identify them. If those are more confusing than not having them, then we can drop that and just describe them in terms of who interacts with them.

> * First, is IngressController a workload API or a configuration API?  It isn't cluster-scoped, and it isn't singleton, but the cluster admin does use it to configure cluster infrastructure (namely the default ingresscontroller, which handles several critical routes).

@deads2k is probably the expert here but I think the IngressController is a workload API more than it's a configuration API. If users are creating `IngressControllers` they are probably using them with their workloads right? So we want that not to break down the line, we shouldn't change the defaults here because it could affect how traffic is routed to the workload.

The default ingress controller is the exception here because it's being overloaded to provide cluster critical infrastructure.

> * For the sake discussion, let's say that IngressController is a configuration API; would I be expected to identify it as such explicitly in the PR description or API documentation?

I think this is something we could/should discuss. If we want to have these conventions and include these differences between workload and configuration APIs, perhaps we can lint/warn users about changes to their API based on some tag
`// +openshift:api:Type=Workload|Configuration`.

> * Would I be expected to make IngressController cluster-scoped and singleton, or justify why it is unlike a typical configuration API in these respects?

I think the IngressController is a workload API, but for arguments sake. Yes, you would have to justify why it isn't. I had this conversation with @deads2k when introducing the ControlPlaneMachineSet. He suggested it was a Configuration API which I agreed with, but had to justify why I wanted it singleton-namespaced rather than singleton-cluster. We made an exception there.

> * When we originally added IngressController, we envisioned that we _might_ allow regular users to create ingresscontroller objects in their own namespaces; does the configuration vs. workload dichotomy preclude that use-case, would it force us to categorize IngressController as a workload API, or what?

In that case I would expect it to be classed as a Workload API, but I already thought it was so maybe I've misunderstood the use cases it fulfils. Do users today not have the ability, should an admin allow, to create IngressControllers and provide networking into their namespaces?

**Comment by Miciah** [comment]
> > I still wonder to what extent this is descriptive, and to what extent it's prescriptive. Are we going to hold API authors stringently to these conventions? For example, let's say I were introducing the IngressController API today, as a new API.
> 
> Is your suggestion to drop the bit that describes what these typically look like? We know we have exceptions to this (I recently added a configuration API that's not cluster scoped for example) but these are more, general rules for how you might identify them. If those are more confusing than not having them, then we can drop that and just describe them in terms of who interacts with them.

I'm not suggesting dropping anything, but rather clarifying why the distinction between configuration and workload matters.  I think this answers the question: "these are more, general rules for how you might identify them".  That is, the reason this document lays out the distinction is so that API authors can select the appropriate model (configuration API or workload API) for thinking about the API and know which set of conventions applies, with the understanding that the model itself is a loose framework and the conventions defined later in the document are more strict rules.  

> > * First, is IngressController a workload API or a configuration API?  It isn't cluster-scoped, and it isn't singleton, but the cluster admin does use it to configure cluster infrastructure (namely the default ingresscontroller, which handles several critical routes).
> 
> @deads2k is probably the expert here but I think the IngressController is a workload API more than it's a configuration API. If users are creating `IngressControllers` they are probably using them with their workloads right? So we want that not to break down the line, we shouldn't change the defaults here because it could affect how traffic is routed to the workload.

I think everything in the cluster exists ultimately for the purpose of supporting user workload.  It seems to me that it's a matter of how closely connected resources are to the user workload, and that proximity varies by use-case.  The cluster admin could be using multiple ingresscontrollers for general sharding use-cases, which seems more like a configuration-API use-case, or for isolating some specific workload to its own ingresscontroller, which seems more like a workload-API use-case.  

> The default ingress controller is the exception here because it's being overloaded to provide cluster critical infrastructure.

Fair enough.  

> > * For the sake discussion, let's say that IngressController is a configuration API; would I be expected to identify it as such explicitly in the PR description or API documentation?
> 
> I think this is something we could/should discuss. If we want to have these conventions and include these differences between workload and configuration APIs, perhaps we can lint/warn users about changes to their API based on some tag `// +openshift:api:Type=Workload|Configuration`.

Maybe, but we don't necessarily need to be that strict, especially if the configuration-versus-workload dichotomy may not apply cleanly to all APIs.  

> > * Would I be expected to make IngressController cluster-scoped and singleton, or justify why it is unlike a typical configuration API in these respects?
> 
> I think the IngressController is a workload API, but for arguments sake. Yes, you would have to justify why it isn't. I had this conversation with @deads2k when introducing the ControlPlaneMachineSet. He suggested it was a Configuration API which I agreed with, but had to justify why I wanted it singleton-namespaced rather than singleton-cluster. We made an exception there.

That seems fine, as long as we're clear about which things are suggestions, which things are rules that may be violated with sufficient justification, and which things are inviolable rules.  

> > * When we originally added IngressController, we envisioned that we _might_ allow regular users to create ingresscontroller objects in their own namespaces; does the configuration vs. workload dichotomy preclude that use-case, would it force us to categorize IngressController as a workload API, or what?
> 
> In that case I would expect it to be classed as a Workload API, but I already thought it was so maybe I've misunderstood the use cases it fulfils. Do users today not have the ability, should an admin allow, to create IngressControllers and provide networking into their namespaces?

The ingress operator ignores ingresscontrollers outside of the "openshift-ingress-operator" namespace.  The cluster admin could delegate permission to create ingresscontrollers in that namespace, and we could conceivably add the capability to manage ingresscontrollers in other namespaces (possibly by running a separate instance of the ingress operator in each additional namespace).

**Comment by deads2k** [comment]
ingress is an API that isn't quite workload, but cluster-admins create more than one of them.  I think this guidance is good

/lgtm

/hold

hold to fix up the typos from Miciah's review.

**Comment by JoelSpeed** [comment]
Typos resolved

**Pull request merged**
