### PR TITLE
Update `External` platform type EP with implementation histotry block

### PR DESCRIPTION
**Pull request by lobziik**
This PR proposes updates that contain links to the merged and upcoming changes for `openshift/api` in regards to the `External` platform implementation.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
very nice to update here as well, thanks!
/lgtm

**Comment by dhellmann** [comment]
This is OK, but generally we'd rather have a tracking link at the top of the doc that people can go to look at for all of the implementation work. That avoids having to come back here and add follow-up patches like this and keeps the ticket system as the source of information for work-in-progress.

/approve

**Comment by elmiko** [comment]
this is probably an oversight on my part, i don't think we ever created a jira card to capture backing out these changes.  it's no excuse, but a lesson for next time to improve our process.

**Pull request merged**
