### PR TITLE
rename template to enhancement_template

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by wking** [comment]
Hah, was I not convincing enough when I removed the `enhancements-` prefix in #3? ;)

**Comment by bparees** [comment]
well it's not in the "enhancements" directory anymore

**Comment by wking** [comment]
This whole repository is about enhancements.

**Comment by bparees** [comment]
> This whole repository is about enhancements.

1) not now that the git commit guidelines are going in here (this is where i was directed to put them..[shrug])
2) if i see a file named "template.md" that tells nothing about what it is a template for, regardless of repository name or purpose.  I may be able to make assumptions, but why not make it explicit?

**Pull request merged**
