### PR TITLE
ovn ns ipsec

### PR DESCRIPTION
**Pull request by yuvalk**
- ovn-ns-ipsec WIP
- added proposal part
- completed the plan section

### CODE REVIEW

**Comment by yuvalk** [comment]
/hold
I guess this is still very much WIP

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. It does not appear to be linked to a valid Jira ticket. Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. It does not appear to be linked to a valid Jira ticket. Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by zshi-redhat** [comment]
@yuvalk  do you have plan to update this enhacement PR in 4.15 cycle?

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. It does not appear to be linked to a valid Jira ticket. Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by zshi-redhat** [comment]
superseded by https://github.com/openshift/enhancements/pull/1521

**Pull request closed without merging**
