### PR TITLE
stability: point to point network check

### PR DESCRIPTION
**Pull request by deads2k**
This helps identify one common root cause of the "openshift-apiserver is down!" problems.

### CODE REVIEW

**Comment by danwinship** [comment]
See also https://issues.redhat.com/browse/SDN-372

**Comment by sanchezl** [comment]
Superseded by https://github.com/openshift/enhancements/pull/289

**Comment by danwinship** [comment]
> Superseded by #289

so... should this be closed?

**Comment by deads2k** [comment]
superceded

**Pull request closed without merging**
