### PR TITLE
Update OWNERS: add rvanderp3

### PR DESCRIPTION
**Pull request by fabianofranz**
Adding Richard Vanderpool, team lead of SPLAT, to the list of approvers.

### CODE REVIEW

**Comment by fabianofranz** [comment]
fyi @kwoodson @rvanderp3

**Comment by dhellmann** [comment]
I'll approve this with a hold so we can get @rvanderp3's ack.

/approve
/lgtm
/hold

**Comment by rvanderp3** [comment]
ack!

**Comment by sdodson** [comment]
I think the ack was supposed to be in the form of
/hold cancel

**Comment by rvanderp3** [comment]
> I think the ack was supposed to be in the form of
> /hold cancel

Didn't realize that.  Thanks @sdodson !

**Pull request merged**
