### PR TITLE
Developer Catalog Helm 3 Use Cases

### PR DESCRIPTION
**Pull request by kirtiapte**
This document covers Developer Catalog Helm 3 Use Cases

### CODE REVIEW

**Comment by sbose78** [comment]
Thank you @kirtiapte for putting this up here, I will review.

**Comment by russellb** [comment]
@sbose78 can you take another look at this?  It looks like this should just be merged as-is, or integrated as a section of the merged helm support enhancement?

**Comment by sbose78** [comment]
We can close this, this has already been absorbed in #175 .

**Pull request closed without merging**
