### PR TITLE
Update the add page customization examples and add hint to use the snippet

### PR DESCRIPTION
**Pull request by jerolimov**
Replaced invalid option IDs with some real examples. Added also a small hint for the snippet.

/assign @christianvogt 
/cc @christianvogt @andrewballantyne

### CODE REVIEW

**Comment by christianvogt** [comment]
/lgtm

thanks for updating these

@spadgett could you approve

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
Should I add some empty sections to fix the template linter similar to https://github.com/openshift/enhancements/blob/master/enhancements/console/internationalization.md?

```
➜  enhancements git:(customize-add-page-update-example) hack/template-lint.sh
Checking enhancements/console/customize-add-page.md
enhancements/console/customize-add-page.md missing "## Design Details"
enhancements/console/customize-add-page.md missing "#### Dev Preview -> Tech Preview"
enhancements/console/customize-add-page.md missing "#### Tech Preview -> GA"
enhancements/console/customize-add-page.md missing "#### Removing a deprecated feature"
enhancements/console/customize-add-page.md missing "### Upgrade / Downgrade Strategy"
enhancements/console/customize-add-page.md missing "## Implementation History"
enhancements/console/customize-add-page.md missing "## Drawbacks"
```

**Review by andrewballantyne — APPROVED** [review]
Thanks!

**Comment by dhellmann** [comment]
> Should I add some empty sections to fix the template linter similar to https://github.com/openshift/enhancements/blob/master/enhancements/console/internationalization.md?

For now, yes, please do. I'm hoping to review the enhancement template soon, but I don't want your work to be blocked on that meta conversation.

**Comment by jerolimov** [comment]
Updated to include requirements from `hack/template-lint.sh`. PTAL.

**Comment by dhellmann** [comment]
/approve

Thanks, @jerolimov!

**Pull request merged**
