### PR TITLE
NE-585 Update enhancement after implementation

### PR DESCRIPTION
**Pull request by candita**
API PR https://github.com/openshift/api/pull/1127/files
Operator PR: https://github.com/openshift/cluster-ingress-operator/pull/712 (WIP until API PR merges)

### CODE REVIEW

**Comment by sdodson** [comment]
If you link to the PR with the implementation that matches this I'd be happy to approve and merge this.

**Comment by candita** [comment]
@sdodson @deads2k would you like to review this?  I think I've made the last additions.

**Comment by candita** [comment]
@sdodson @Miciah @deads2k  I've made the final updates on this, post-implementation.  Could you PTAL?

**Comment by Miciah** [comment]
The linter has a new requirement:
```
 enhancements/ingress/haproxy-max-connections-tuning.md missing "### Workflow Description" 
```
This requirement is redundant because the topic is already covered by the "User Stories" and "Open Questions" sections, and the requirement wasn't there when the PR was posted, so I'm overriding it.

/override ci/prow/markdownlint

**Comment by candita** [comment]
#linter change added 3 days ago
/override

**Pull request merged**
