### PR TITLE
Update flow control API enhancement to match final implementation

### PR DESCRIPTION
**Pull request by alanconway**
- Remove "policy" field.
- Clean up examples & text.

### CODE REVIEW

**Comment by alanconway** [comment]
@Pranjal-Gupta2 removed the "lowest limit"  comment, please re-review.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, LOG-1043, has status "Closed, Done". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by alanconway** [comment]
This PR is no longer relevant, see is https://github.com/openshift/cluster-logging-operator/pull/1682.

**Comment by alanconway** [comment]
/assign @periklis 
Peri can you approve/lgtm this? It's an old PR that I thought had merged, but  went stale instead. Minor updates to the flow control enhancement.

**Pull request merged**
