### PR TITLE
fix a note about SC alerts in csi-migration enhancement

### PR DESCRIPTION
**Pull request by RomanBednar**
Implementation of alerts about default storage class count moved to [CSO](https://github.com/openshift/cluster-storage-operator/pull/276)

### CODE REVIEW

**Comment by dhellmann** [comment]
/override ci/prow/markdownlint

The only failures are from template updates since this doc was written originally, and those can be ignored.

**Review by bertinatto — COMMENTED** [review]
/lgtm
/approve

**Comment by dhellmann** [comment]
It looks like there's a legitimate issue with the linter.

```
enhancements/storage/csi-migration.md: could not extract meta data from header: yaml: line 8: found character that cannot start any token
[72](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_enhancements/1111/pull-ci-openshift-enhancements-master-markdownlint/1524889936984018944#1:build-log.txt%3A72)
```

/hold

**Comment by dhellmann** [comment]
https://github.com/openshift/enhancements/pull/1117 should make the metadata linter ignore existing files

/hold cancel
/override ci/prow/markdownlint

**Pull request merged**
