### PR TITLE
Remove tenant configuration from loki output configuration.

### PR DESCRIPTION
**Pull request by alanconway**
The collector is not the correct point to set tenancy for Loki.  Tenancy is determined downstream by the Loki instance and associated tools.

Removed the tenant fields.
Corrected the definition of the cluster label to be in line with cloudwatch (use the openshift name)

/cc @periklis

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by alanconway** [comment]
@jcantrill 
can you give me an lgtm/approve? Not controviersial, checked out by @periklis

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by sdodson** [comment]
/hold
@alanconway Can you please fix the markdownlint problems? Looks like a few sections from the template are missing.

**Comment by alanconway** [comment]
/unhold

@jcantrill I need another LGTM, the linter got stricter since last this merged.

**Pull request merged**
