### PR TITLE
Move drawbacks section up to a place of prominence, rework a few other section orderings

### PR DESCRIPTION
**Pull request by bparees**
I think this creates a better flow:

motivation - why do we want to do this
user stories - who is asking for it/what do they want to do
goals - concrete interpretation of the stories
non-goals - concrete interpretation of the stories
proposal - how we plan to do it
drawbacks - reasons not to do it (technical or business), subsection of Proposal

while bringing the "drawbacks" section up to front and center instead of buried
at the end.

I would probably argue for moving "alternatives" up from where it is now (near the bottom) also, but i'm ok letting it sit for now

### CODE REVIEW

**Comment by bparees** [comment]
@dhellmann i'm willing to split this out into separate PRs if more discussion is needed, but this fixes some of the structural ordering issues that had been bothering me about the current EP section ordering

**Comment by dhellmann** [comment]
I like this. I'll end up having to change my PR adding the workflow section, but I can do that.

/approve

/cc @kikisdeliveryservice

**Review by kikisdeliveryservice — COMMENTED** [review]
+1 moving user stories up and general +1 in moving drawbacks up but I feel like it would be better moved up to right under the Proposal section? I'd understand the drawbacks better, if I read the proposal first no?

**Comment by bparees** [comment]
> I feel like it would be better moved up to right under the Proposal section? I'd understand the drawbacks better, if I read the proposal first no?

i think it depends on what the drawbacks are.  We have both "drawbacks" and "risks" (and also alternatives, which is related).

in my mind, the "drawbacks" are more about drawbacks to the concept/idea of doing this overall, and thus comes right after the motivation for why we *do* think we should be doing this.

risks are where you talk about limitations/challenges/technical obstacles to the design/implementation discussed in the proposal

**Comment by zaneb** [comment]
> in my mind, the "drawbacks" are more about drawbacks to the concept/idea of doing this overall, and thus comes right after the motivation for why we _do_ think we should be doing this.

I guess I don't really agree here. Every design choice comes with trade-offs and it's important to go into a decision with a clear idea of what trade-offs you're making. Putting the "Drawbacks" before the "Proposal" (so that it is implicitly responding only to the idea of doing anything at all, as opposed to the concrete proposal) seems like an invitation to not think too hard about that.

Maybe this calls for something like an additional "Counter-arguments" subsection under "Motivations" instead?

**Comment by bparees** [comment]
@kikisdeliveryservice @zaneb ok i think i'm convinced, i've pushed a new commit that relocates the drawbacks section to be part of the proposal, but retains the additional description about what the Drawbacks section should cover.

I debated trying to keep it split (i.e. an "anti-motivation" section, and then a drawbacks section) but that's probably not worth splitting and i couldn't come up with a good word for "anti-motivation" other than drawbacks anyway.

**Review by kikisdeliveryservice — APPROVED** [review]
/lgtm

**Pull request merged**
