### PR TITLE
OCPSTRAT-736: installer: support of extending workers to AWS Wavelength

### PR DESCRIPTION
**Pull request by mtulio**
This enhancement introduces the support of installing a cluster on AWS extending worker nodes to Wavelength - as edge zones.

This is part of the feature [OCPSTRAT-736](https://issues.redhat.com/browse/OCPSTRAT-736), covering the following epics/goals:

- Goal 1 ([SPLAT-1125](https://issues.redhat.com/browse/SPLAT-1125)): Fully automate the network requirements to deploy edge nodes on AWS Wavelength
- Goal 2 ([SPLAT-1218](https://issues.redhat.com/browse/SPLAT-1218)): Support Installing a cluster in existing VPC (BYO VPC) extending nodes to AWS Wavelength
- Goal 3 ([SPLAT-1219](https://issues.redhat.com/browse/SPLAT-1219)): Document the steps to extend existing OpenShift clusters running on AWS to the edge nodes in AWS Wavelength
- Goal 4 ([SPLAT-1220](https://issues.redhat.com/browse/SPLAT-1220)): Carrier IP Address assignment when creating EC2 instances with Machine API

### CODE REVIEW

**Comment by mtulio** [comment]
Would you mind taking a look at this proposal?
/assign @rvanderp3 @JoelSpeed @patrickdillon

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, OCPSTRAT-736, has status "In Progress". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, OCPSTRAT-736, has status "In Progress". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, OCPSTRAT-736, has status "Release Pending". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by mtulio** [comment]
For some reason this EP has been lost when wrapping up the feature last year.

The feature has been added to 4.15+. I am reopening this PR to formalize the flow.

/assign @rvanderp3 @JoelSpeed @patrickdillon 

/reopen

**Pull request closed without merging**
