### PR TITLE
Fix typos and outdated info on bundle enhancement doc

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@shawn-hurley PTAL. Just a small PR to correct some typos and outdated information due to recently merged PR from Kevin to keep the consistency across the documentation.

**Comment by shawn-hurley** [comment]
It looks like we are adding versioning to the labels and annotations file keys, but by adding a version to each key, we may allow for someone in the future to have a .v2 key for one of the fields and .v1 for another. 

Is this the desired behavior?

**Comment by dinhxuanvu** [comment]
> It looks like we are adding versioning to the labels and annotations file keys, but by adding a version to each key, we may allow for someone in the future to have a .v2 key for one of the fields and .v1 for another.
> 
> Is this the desired behavior?

I believe that is the intention. @kevinrizza @ecordell Can you confirm this?

**Comment by kevinrizza** [comment]
@dinhxuanvu @shawn-hurley yes the intention is that we can update the spec and clients that read these images can tell which version of the spec the images are on and handle the data accordingly.

**Comment by shawn-hurley** [comment]
The question that I have is in the future do we want to have to handle this situation:
` operators.operatorframework.io.bundle.package.v2=<new-package-name-format`
`operators.operatorframework.io.bundle.mediatype.v1=registry+v1` 

where we can mix and match versions?

**Comment by kevinrizza** [comment]
> The question that I have is in the future do we want to have to handle this situation:
> ` operators.operatorframework.io.bundle.package.v2=<new-package-name-format`
> `operators.operatorframework.io.bundle.mediatype.v1=registry+v1`
> 
> where we can mix and match versions?

I don't think the intention is necessarily to guarantee support for every possible combination, just to give us an indication of what version of the spec the image is currently on. But yes, in some cases mixing and matching is now possible (and totally reasonable).

**Comment by shawn-hurley** [comment]
Can you explain where it would be reasonable? 

If the intention is not to support every possible combination how are we going to show that key1 is only compatible with key2 in these versions? 

Would it be safer to have a new "version" key where you can have `operators.operatorframework.io.bundle.version=v1.2`and it is responsible for reporting the version for every field? That way we can clearly write the rules for each key based on a version?

**Comment by russellb** [comment]
@dinhxuanvu @shawn-hurley @kevinrizza This PR stalled out many months ago.  There are some obvious typo fixes included that we should just merge quickly.  Can the PR get updated to only include what we can just merge and drop anything that needs any more discussion?  Thanks!

**Pull request closed without merging**
