### PR TITLE
update owners list

### PR DESCRIPTION
**Pull request by dhellmann**
Prune the list of people no longer contributing to OpenShift and add
missing team leads.

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
/approve
/lgtm

note: i know there is an unresolved discussion about how we want to manage approval permissions in this repo in the future.  This approval should not be taken as an explicit or implicit endorsement of the current model, but it seems best to at least clean up the list in its current form, regardless of whether we decide to change how permissions are assigned in the (possibly near) future.

**Comment by bn222** [comment]
LGTM

**Comment by jan** [comment]
@dhellmann bruh, why you tag me?

**Comment by jan--f** [comment]
@jan that looks like a bug in a bot, you got tagged by mistake, I was supposed to be tagged.

@dhellmann seems like the `openshift-ci` bot can't deal with `-` in a username.
 https://github.com/openshift/enhancements/pull/1434#issuecomment-1614706241
`@jan--f` became `@jan`
`@s-urbaniak` became `@s`

**Comment by dhellmann** [comment]
@jan & @jan--f, that ping was from a scripting error. I fixed the script, but not before posting its output, unfortunately. Sorry for the noise.

**Pull request merged**
