### PR TITLE
Add "Build OKD for ppc64le" proposal

### PR DESCRIPTION
**Pull request by mjturek**
Add proposal to build and publish ppc64le payloads alongside x86_64 builds.

### CODE REVIEW

**Comment by mjturek** [comment]
I know this is a bit bare bones at the moment but I'd like to start a conversation about how we can start building and publishing for ppc64le. If there's something that you think should be detailed or discussed, please bring it up here!

**Comment by LorbusChris** [comment]
Thanks for working on this @mjturek!

I'd suggest we approach Fedora and/or CentOS infra folks to discuss the resource requirements with them.

Some additional details on how the builds will be done would be great, too.
For OKD on x86, FCOS is built on an external Jenkins cluster, while container builds are done on Prow (the majority of OKD containers are mirrored/promoted OCP CI builds, the rest are also built on Prow and directly tagged into the `origin` namespace.)

How do you envision the process be for ppc64le?

**Comment by clnperez** [comment]
/remove-lifecycle stale

We've been working on a prow cluster on Power inside of Power VS (part of IBM Cloud). Once we have that working we can extend what we've learned there to OKD. It's just taking a bit longer as there are no upstream images for prow on Power (yet).

**Comment by LorbusChris** [comment]
We might still want to do this eventually. We're working on ARM64 CI and OKD builds now, which should serve as a blueprint for further archs.

/remove-lifecycle stale

**Comment by clnperez** [comment]
@LorbusChris we're getting a bit more interest from customers. You'd mentioned getting with the Fedora and/or CentOS infra folks. Is there a process there? Do you know who to ping?

**Comment by LorbusChris** [comment]
Hi @clnperez,
I think that specific comment is now obsolete.
OKD is built on OpenShift's multi-cluster Prow CI system, so there'd have to be at least one ppc64le build farm cluster set up and added to Prow.
I think work for that is already on its way, but I'm not involved in that effort. Once that's set up though, and there are per-component CI builds and CI release payloads, it'll be possible to also create OKD release payloads for that arch.

**Comment by clnperez** [comment]
Yep, that's underway (and I've been keeping informed). Sounds like what we do need is fcos builds first -- and that's a conversation that's happening (kind of) here: https://github.com/coreos/fedora-coreos-tracker/issues/987 & https://github.com/coreos/coreos-assembler/issues/2473

**Pull request closed without merging**
