### PR TITLE
add must-gather current state

### PR DESCRIPTION
**Pull request by deads2k**
The enhancement indicates the current state of must-gather

/assign @mfojtik 
@openshift/openshift-team-master

### CODE REVIEW

**Comment by mfojtik** [comment]
I would like to elaborate on the related objects concept, I think it fits to this enhancement and it might be useful to explain how it works.

**Comment by soltysh** [comment]
> I would like to elaborate on the related objects concept, I think it fits to this enhancement and it might be useful to explain how it works.

Definitely something all operator authors should be aware and should comply with.

**Comment by aravindhp** [comment]
> > I would like to elaborate on the related objects concept, I think it fits to this enhancement and it might be useful to explain how it works.
> 
> Definitely something all operator authors should be aware and should comply with.

It would help if this is clearly documented and messaged out to all operator authors, hopefully not in the form of BZs.

**Pull request merged**
