### PR TITLE
SPLAT-653: Updates in installer/aws-localzones

### PR DESCRIPTION
**Pull request by mtulio**
Punctual updates related/caught in the Local Zones Phase 2 implementation: 
 https://github.com/openshift/installer/pull/7137

### CODE REVIEW

**Comment by mtulio** [comment]
@patrickdillon @JoelSpeed @rvanderp3 - would you mind taking a look at those updates? The related PRs are already merged for 4.14.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, RFE-2782, has status "Accepted". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, RFE-2782, has status "Accepted". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Comment by mtulio** [comment]
/reopen
/remove-lifecycle stale
This feature was delivered in 4.14, it is small update.

@patrickdillon would you mind to review in this short updates for Local Zones?

**Pull request merged**
