### PR TITLE
Enhancement: OCP cluster pre-upgrades with Leapp

### PR DESCRIPTION
**Pull request by Monnte**
Proposal to add an opt-in feature to automatically scan cluster nodes before an upgrade of the OS that crosses major versions to detect possible problems such as running on hardware that is deprecated in the upgrade target OS.

### CODE REVIEW

**Comment by dhellmann** [comment]
#1555 is changing the enhancement template in a way that will cause the header check in the linter job to fail for existing PRs. If this PR is merged within the development period for 4.16 you may override the linter if the only failures are caused by issues with the headers (please make sure the markdown formatting is correct). If this PR is not merged before 4.16 development closes, please update the enhancement to conform to the new template.

**Comment by oarribas** [comment]
Maybe this can be added to the Managed Upgrade Operator [1].
While it was created for doing pre-upgrade checks (and other tasks) in Managed OpenShift clusters, it could be used also in self-managed clusters. The Leapp check could be another of the pre-checks done by that operator.


[1] https://github.com/openshift/managed-upgrade-operator/

**Comment by dhellmann** [comment]
(automated message) This pull request is closed with lifecycle/rotten. The associated Jira ticket, OAMG-10748, has status "In Progress". Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

**Pull request closed without merging**
